### ISSUE TITLE
Stardock Fences out of date, latest is 5.0.4.1

### ISSUE THREAD

**Issue by asheroto** [virtualex-itv/chocolatey-packages#13]
Hello,

Stardock Fences is on version 5.0.4.1 but the latest Choco package shoes 4.03.

https://community.chocolatey.org/packages/stardock-fences

If you are no longer interested in maintaining the package I am happy to assist. Using the same name on Chocolatey as a package maintainer.

Thanks! 😊

**Comment by virtualex-itv** [comment]
thanks for bringing this to my attention.  I don't actively use this software so I don't keep up with the latest releases.  If you have a working update, please feel free to submit a PR for review so I can update and package a new release.

**Comment by virtualex-itv** [comment]
The updated package has been pushed and awaiting moderation

**Comment by asheroto** [comment]
Are you guys monitoring the version changes? This is out of date again by two versions.

https://www.stardock.com/products/fences/history

You can use a tool like VisualPing to monitor changes or [AU](https://github.com/chocolatey-community/chocolatey-au).

If you want to add me as a package maintainer I can help keep this up-to-date, but no worries if not.
