### ISSUE TITLE
OpenLens outdated

### ISSUE THREAD

**Issue by Huskydog9988** [virtualex-itv/chocolatey-packages#9]
Sorry to ignore your template, but openlens is starting to drift out of date. Currently the most recent stable version on choco is `6.4.6`, while the openlens build repo has the latest version at `6.4.13`.  Because it seems like you use automatic packages, I think its safe to assume the update script is broken, but I can't find an issue with it at a cursory glance. (Also thanks for setting this up in the first place, its really convenient.)

**Comment by virtualex-itv** [comment]
@Huskydog9988 - thanks for letting me know and apologies for the delayed response!  I will look into it and fix promptly!

**Comment by virtualex-itv** [comment]
fixed.  please wait for the updated packages to be approved
